name: Diffblue write incremental tests for a Java PR
on:
  pull_request:
    types:
      - opened
    paths:
      - '**.java'
concurrency:
  # Only allow one run of the workflow per branch to run at a timea
  group: $
  cancel-in-progress: true
jobs:
  Test:
    runs-on: ubuntu-22.04
    env:
      JVM_ARGS: -Xmx8192m
    steps:
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup Git Credentials
        uses: fregante/setup-git-user@v2
      - name: Generate patch file from latest changes
        run: |
          git diff ${{ github.event.pull_request.base.sha }}...HEAD > "$GITHUB_WORKSPACE/changes.patch"
          cat "$GITHUB_WORKSPACE/changes.patch"
      - name: Download Diffblue Cover
        run: |
          mkdir -p "$RUNNER_TEMP/dcover"
          cd "$RUNNER_TEMP/dcover"
          curl --silent --show-error --location --output "diffblue-cover-cli.zip" "https://release.diffblue.com/2023.11.01/d8594edc7f1cdabf71ee007132b5800765f9762b7838997fb02014d1489b9cfd/diffblue-cover-cli-2023.11.01.zip"
          unzip -q "diffblue-cover-cli.zip"
          rm -f "diffblue-cover-cli.zip"
          echo "$RUNNER_TEMP/dcover" >> "$GITHUB_PATH"
      - name: Compile project
        run: mvn --batch-mode --no-transfer-progress clean compile
      - name: Activate Diffblue Cover
        run: dcover activate "${{ secrets.DIFFBLUE_COVER_LICENSE_KEY }}"
      #- name: Create all unit tests
      #  run: dcover create  --maven --batch
      - name: Create unit tests based on diff
        run: dcover create --maven --batch --patch-only "$GITHUB_WORKSPACE/changes.patch"
      - name: Add the new tests
        run: |
          git add -f "*/*DiffblueTest.java"
          git commit -am "Incremental Diffblue Test"
          git push origin HEAD:${{ github.head_ref }}
